### ISSUE TITLE
Pulls Jest 21 to a project

### ISSUE THREAD

**Issue by bebraw** [bvaughn/jest-react-profiler#2]
Since there's `"jest": "^21",` in deps, looks like the profiler pulls Jest 21 into a project.

Do you think it would be possible to drop this requirement? Let's do peer deps for supported Jest range instead?

**Comment by bvaughn** [comment]
You're right. I should have declared it as either a peer dependency or better still just via the docs. Want to send me a PR?

**Comment by bebraw** [comment]
Sure, will do.

**Comment by bvaughn** [comment]
Excellent. I'd say we should just remove it as a dependency entirely and just document the minimum version in the readme.
