### ISSUE TITLE
Profiler onRender was never called.

### ISSUE THREAD

**Issue by rwieruch** [bvaughn/jest-react-profiler#4]
Hello @bvaughn 

Just stumbled upon this Profiler impl. for Jest. Super excited about all your recent work for React Profiler 👍 

In my case, I ran into the following error: 

```
Profiler onRender was never called.
   
This may indicate that you are using a version of React that does not support profiling.
```

My test in Jest looks like the following:

```
it('Message', () => {
    const MessageWithProfiler = withProfiler(Message);
 
    renderer.create(
      renderToString(<MessageWithProfiler />),
    );
 
    expect(MessageWithProfiler).toMatchNumCommits();
  });
```

Is it because you are using a different renderer?

**My versions:**

React: 16.8.6
Jest: 22.2.2

which should be okay regarding the peer dependencies used by jest-react-profiler.

Any hints on why this may fail? Thanks for your time!

**Comment by bvaughn** [comment]
The `Profiler` does not get called by the server renderer (`renderToString`). Nothing to do with this lib/util 😄 

Despite its name, the `onRender` callback is called on _commit_ and there is no "commit" phase on the server– so the `Profiler` was implemented as a no-op for the server renderer. (It won't break the app, but it won't collect or log any metrics either.)

Related React issue: https://github.com/facebook/react/issues/13673

**Comment by rwieruch** [comment]
Just to clarify: Which renderer should be used in a Jest test then? Thanks for your time @bvaughn

**Comment by bvaughn** [comment]
It depends on what you're testing I suppose 😄 There are some cases where it makes sense to use `renderToString` but I think more commonly it would make sense to use `render`. I don't know your test setup though

**Comment by rwieruch** [comment]
In case someone is interested in this issue: I have created a small example application over [here](https://github.com/rwieruch/jest-react-profiler-example), because a client of mine is doing experimentations with the new React Profiler and I wanted to showcase it. The test file can be found [here](https://github.com/rwieruch/jest-react-profiler-example/blob/master/src/App.spec.js). It uses three different renderers, whereas I am not super sure what every renderer does under the hood, however, the renderer for Jest doesn't seem to work with the Profiler API. But the other two renderers do the job.

Minor API note: First I thought `toHaveCommittedTimes` wouldn't work when updating the state of a component, because I assumed it would increment the count of commited times  (see comment in test code).

@bvaughn really looking forward to more React Profiler stuff 👍
